### ISSUE TITLE
如何通过加载Plugin实现功能呢

### ISSUE THREAD

**Issue by Ptkatz** [qwqdanchun/Creeper-Awww-man#1]
DCRat的Plugin加载功能我觉得非常好用，而且可以减小Client的体积，Creeper-Awww-man可以实现这个功能吗

**Comment by qwqdanchun** [comment]
这只是一个用于测试动态编译加载，以及卸载assembly的项目，所以部分不适合动态编译的功能都直接内置于client中

**Comment by Ptkatz** [comment]
师傅方便加一下微信吗，交流学习

**Comment by qwqdanchun** [comment]
联系方式看这里
https://www.qwqdanchun.com/
